name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Use Corepack to activate a specific pnpm version instead of global npm install
      - name: Enable Corepack
        run: corepack enable
      - name: Activate pnpm 10
        run: corepack prepare pnpm@10 --activate
      - name: Install deps
        run: pnpm i
      - run: pnpm run typecheck
      - run: pnpm run lint
      - run: pnpm run test

